# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in aoc2025.gemspec
gemspec

gem "irb", "~> 1.15"

gem "rake", "~> 13.0"

gem "minitest", "~> 5.16"

gem "standard", "~> 1.3"


gem "rubocop", "~> 1.81"
